BEGIN;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "albumArtist" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "movie" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "releaseYear" INTEGER;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "releaseDate" TIMESTAMP(3);

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "language" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "explicit" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "composer" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "lyricist" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "producer" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "remixer" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "copyright" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "publisher" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "description" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "trackNumber" INTEGER;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "discNumber" INTEGER;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "coverMimeType" TEXT;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "coverWidth" INTEGER;

ALTER TABLE "Track"
ADD COLUMN IF NOT EXISTS "coverHeight" INTEGER;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "audioHash" TEXT;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "codec" TEXT;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "bitrate" INTEGER;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "sampleRate" INTEGER;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "bitsPerSample" INTEGER;

ALTER TABLE "MusicFile"
ADD COLUMN IF NOT EXISTS "channels" INTEGER;

COMMIT;

